[server]
headless = true
maxUploadSize = 400

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#A02041"
backgroundColor = "#F5F5F6"
secondaryBackgroundColor = "#E7E7E9"
textColor = "#25272B"
font = "sans serif"
